apiVersion: v2
name: ssp-eks-addons
description: A Helm chart demonstrating SSP ArgoCD AddOns management with GitOps 
type: application
version: 0.0.1

dependencies:
- name: prometheus
  condition: prometheus.enabled
  version: 0.0.1
  repository: file:///dependencies/prometheus