---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons 
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: git@github.com:aws-samples/eks-gitops-crossplane-argocd.git
    targetRevision: HEAD
    path: workloads
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m      