{{- if .Values.certManager -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-root 
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://github.com/kcoleman731/argo-add-ons
    path: infra/cert-manager
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m 
{{- end -}} 