apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: prometheus
  {{- if (lookup "v1" "configmap" "" "prometheus-config") }}
    repoURL: {{ (lookup "v1" "configmap" "" "prometheus-config").data.repoURL }} 
  {{ else }}
    repoURL: {{ .Values.spec.source.repoURL }}
  {{- end }}
    targetRevision: 14.6.0
    helm: 
      valueFiles:
      - values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true