apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.source.chart }}
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    chart: {{ .Values.spec.source.chart }}
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true