apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-calico
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: aws-calico
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 0.3.7
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true