apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: agones
    repoURL: https://agones.dev/chart/stable
    targetRevision: 1.15.0
    helm: 
      valueFiles:
      - values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true