apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    helm: 
      releaseName: metrics-server
      version: 3.5.0
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc